// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdqorufvnblxxbaxwrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcW9ydWZ2bmJseHhiYXh3cmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTUyMDQsImV4cCI6MjA2MjYzMTIwNH0.l586LWI6GtYTX7GMNujeHlcWfvEq6fpqRHpyoznL-Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);